foundercore/VegaTestPortal

README.md, src/app/app.module.ts, src/app/core/app-animation.module.ts, src/app/core/app-routing.module.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/dashboard/dashboard.component.spec.ts, src/app/views/dashboard/dashboard.component.ts, src/app/views/home/home.component.html, src/app/views/home/home.component.scss, src/app/views/home/home.component.ts, src/app/views/navbar/navbar.component.html, src/app/views/navbar/navbar.component.scss, src/app/views/navbar/navbar.component.ts
Added styles for navbar components for different device widths
Added navigations transitions
=> Added navigation animation and child routes for home component

src/app/app.module.ts, src/app/core/app-routing.module.ts, src/app/guard/auth.guard.ts, src/app/guard/loggedin.guard.ts, src/app/services/authentication/auth.service.ts, src/app/services/base.service.ts, src/app/services/users/users.service.ts
=> Add Auth Guard for login

src/app/views/register/register.component.html
Password changes to Confirm Password
=> Update Password field text

src/app/views/user-management/user-management.component.html
Uncomment User Management screen
=> Uncomment User Management screen

src/app/views/user-management/user-management.component.html
Uncomment the lines in user component html.
=> Update user-management component

src/app/shared/components/header/header.component.html, src/app/shared/components/header/header.component.scss, src/app/views/navbar/navbar.component.html
=> Fix the user profile menu

src/app/views/dashboard/dashboard.component.scss, src/app/views/home/home.component.scss, src/app/views/navbar/navbar.component.scss
Change in nav component and in head component.
=> Change in nav component and in head component.

src/app/views/dashboard/dashboard.component.scss, src/app/views/home/home.component.scss, src/app/views/navbar/navbar.component.scss
Reverts foundercore/VegaTestPortal#16
=> Revert "Change in nav component and in head component."

src/app/views/dashboard/dashboard.component.scss, src/app/views/home/home.component.scss, src/app/views/navbar/navbar.component.scss
Reverts foundercore/VegaTestPortal#17
=> Revert "Revert "Change in nav component and in head component.""

src/app/shared/components/header/header.component.scss, src/app/views/dashboard/dashboard.component.scss, src/app/views/home/home.component.html, src/app/views/home/home.component.scss, src/app/views/navbar/navbar.component.scss, src/app/views/user-management/user-management.component.scss
Revert my changes in home and navbar component.
=> Revert my changes in home and nav component

src/app/views/navbar/navbar.component.scss
=> Revert change in navbar

src/app/app.module.ts, src/app/shared/components/header/header.component.html, src/app/shared/components/header/header.component.ts, src/app/views/home/home.component.ts, src/app/views/users/profile/profile.component.html, src/app/views/users/profile/profile.component.spec.ts, src/app/views/users/profile/profile.component.ts
=> Set Up user Profile Button

src/app/app.module.ts, src/app/views/dashboard/admin-dashboard/admin-dashboard.component.html, src/app/views/dashboard/admin-dashboard/admin-dashboard.component.spec.ts, src/app/views/dashboard/admin-dashboard/admin-dashboard.component.ts, src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.spec.ts, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts
Add admin and student dashboard skeleton
=> Add admin and student dashboard

src/app/views/home/home.component.html, src/app/views/home/home.component.scss, src/app/views/navbar/navbar.component.scss, src/styles.scss
Change in home and nav component. Ans add scrollbar
=> Change in home and nav component.

angular.json, src/app/views/navbar/navbar.component.html, src/app/views/navbar/navbar.component.ts
=> Build Setup

src/app/views/dashboard/admin-dashboard/admin-dashboard.component.css, src/app/views/dashboard/admin-dashboard/admin-dashboard.component.html
Revert change in admin dashboard.
=> Revert change in admin dashboard

src/app/models/user/user-model.ts, src/app/services/authorization/authorization.service.spec.ts, src/app/services/authorization/authorization.service.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/dashboard/dashboard.component.ts, src/app/views/navbar/navbar.component.html, src/app/views/navbar/navbar.component.ts
Authorization and Access Module
=> Authorization and Access Module

src/app/app.module.ts, src/app/core/app-routing.module.ts, src/app/models/student-batch/student-batch-id-model.ts, src/app/models/student-batch/student-batch-model.ts, src/app/services/student-batch/student-batch.service.spec.ts, src/app/services/student-batch/student-batch.service.ts, src/app/views/navbar/navbar.component.html, src/app/views/student-batch/add-batch-student/add-batch-student.component.html, src/app/views/student-batch/add-batch-student/add-batch-student.component.scss, src/app/views/student-batch/add-batch-student/add-batch-student.component.spec.ts, src/app/views/student-batch/add-batch-student/add-batch-student.component.ts, src/app/views/student-batch/add-batch/add-batch.component.html, src/app/views/student-batch/add-batch/add-batch.component.scss, src/app/views/student-batch/add-batch/add-batch.component.spec.ts, src/app/views/student-batch/add-batch/add-batch.component.ts, src/app/views/student-batch/student-batch-management/student-batch-management.component.html, src/app/views/student-batch/student-batch-management/student-batch-management.component.scss, src/app/views/student-batch/student-batch-management/student-batch-management.component.spec.ts, src/app/views/student-batch/student-batch-management/student-batch-management.component.ts
=> Student Batch Management

src/app/app.module.ts, src/app/core/app-routing.module.ts, src/app/core/constants.ts, src/app/core/token-interceptor.ts, src/app/guard/role.guard.ts, src/app/models/user/user-model.ts, src/app/services/authentication/auth.service.ts, src/app/services/authorization/authorization.service.ts, src/app/shared/components/header/header.component.html, src/app/state_management/_effects/auth.effects.ts, src/app/state_management/_reducers/auth.reducers.ts
Role Guard and removing localstorage
=> Role Guard and removing localstorage  

src/app/views/questions/question-form/question-form.component.html, src/app/views/questions/question-form/question-form.component.ts, src/app/views/questions/question-management/question-management.component.ts
Bugs Fixes For Question Management
=> Bugs Fixes For Question Management

src/app/shared/components/header/header.component.html, src/app/shared/components/header/header.component.scss, src/app/shared/components/header/header.component.ts
=> Navbar changes

package-lock.json, src/app/models/user/user-model.ts, src/app/views/login/login.component.html, src/app/views/login/login.component.scss
Update Username field in the app state
=> Update Username field in the app state

src/app/app.module.ts, src/app/models/questions/search-question-model.ts, src/app/services/question-management/question-management.service.ts, src/app/views/questions/question-management/question-management.component.css, src/app/views/questions/question-management/question-management.component.html, src/app/views/questions/question-management/question-management.component.ts, src/app/views/questions/question-migrate-upload-dialog/question-migrate-upload-dialog.component.html, src/app/views/questions/question-migrate-upload-dialog/question-migrate-upload-dialog.component.scss, src/app/views/questions/question-migrate-upload-dialog/question-migrate-upload-dialog.component.spec.ts, src/app/views/questions/question-migrate-upload-dialog/question-migrate-upload-dialog.component.ts, src/assets/i18n/en.json
Questions Management
o	By default Sort questions by LastUpdatedTime.
o	After Upload the question list should refresh.
o	Add a file name filter in the questions filter section. It should be a text field to be mapped with 'filename' field
o	Remove the Description column
=> Changes in Questions Management

buildspec.yaml, src/app/shared/components/header/header.component.ts
=> add buildspec.yaml

src/app/app.component.ts, src/app/app.module.ts, src/app/models/user/user-model.ts, src/app/services/authorization/authorization.service.ts, src/app/shared/components/dialog-conformation/dialog-conformation.component.html, src/app/shared/components/dialog-conformation/dialog-conformation.component.scss, src/app/shared/components/dialog-conformation/dialog-conformation.component.spec.ts, src/app/shared/components/dialog-conformation/dialog-conformation.component.ts, src/app/state_management/_reducers/auth.reducers.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/questions/question-management/question-management.component.css, src/app/views/questions/question-management/question-management.component.html, src/app/views/questions/question-management/question-management.component.ts, src/app/views/student-batch/add-batch-student/add-batch-student.component.scss, src/app/views/student-batch/add-batch/add-batch.component.ts, src/app/views/student-batch/bulk-upload-batch-students/bulk-upload-batch-students.component.html, src/app/views/student-batch/student-batch-management/student-batch-management.component.scss, src/app/views/user/add-user-dialog/add-user-dialog.component.html, src/app/views/user/add-user-dialog/add-user-dialog.component.ts, src/app/views/user/change-password/change-password.component.html, src/app/views/user/change-password/change-password.component.scss, src/app/views/user/change-password/change-password.component.ts, src/app/views/user/change-password/password-policy.ts, src/app/views/user/user-management/user-management.component.html, src/app/views/user/user-management/user-management.component.ts, src/styles.scss
=> Some Blocker bugs changes

src/app/app.module.ts, src/app/models/test-assignment/test-assignment-request.ts, src/app/services/assignment/test-assignment-service.service.spec.ts, src/app/services/assignment/test-assignment-service.service.ts, src/app/views/assignments/assignment-form/assignment-form.component.html, src/app/views/assignments/assignment-form/assignment-form.component.scss, src/app/views/assignments/assignment-form/assignment-form.component.spec.ts, src/app/views/assignments/assignment-form/assignment-form.component.ts, src/app/views/assignments/assignments-routing.module.ts, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts, src/app/views/assignments/view-assignment/view-assignment.component.html, src/app/views/assignments/view-assignment/view-assignment.component.scss, src/app/views/assignments/view-assignment/view-assignment.component.spec.ts, src/app/views/assignments/view-assignment/view-assignment.component.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts, src/app/views/questions/question-management/question-management.component.html, src/app/views/questions/question-management/question-management.component.ts
=> View,Add,edit Assignment

src/app/shared/components/header/header.component.html, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.html
=> Update Student Dash board

src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts
=> Get Status corrected

src/app/views/assignments/assignments.module.ts, src/app/views/assignments/clone-assignment/clone-assignment.component.css, src/app/views/assignments/clone-assignment/clone-assignment.component.html, src/app/views/assignments/clone-assignment/clone-assignment.component.spec.ts, src/app/views/assignments/clone-assignment/clone-assignment.component.ts, src/app/views/assignments/popups/questions-list/questions-list.component.ts, src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/tests/tests.component.ts
Add clone functionality to tests
=> Add clone functionality to tests

src/app/services/assignment/test-assignment-service.service.ts, src/app/views/assignments/assignment-form/assignment-form.component.ts
=> Update assignment post call.

src/app/views/assignments/tests/tests.component.css, src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/tests/tests.component.ts, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts
Update User messages in the update test screen
=> Update User messages in the update test screen

src/app/views/assignments/popups/test-live/test-live.component.html
=> Fix Live Preview

src/app/views/assignments/models/searchQuestionVM.ts
Set sort column order in test management
=> Set sort column order in test management

src/app/views/assignments/add-students/add-students.component.ts, src/app/views/assignments/assignment-form/assignment-form.component.html, src/app/views/assignments/assignment-form/assignment-form.component.ts, src/app/views/questions/question-form-preview/question-form-preview.component.scss
=> Production bugs

src/app/views/assignments/models/searchQuestionVM.ts, src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/tests/tests.component.ts
Add pagination and search setup in Test screen.
=> Add pagination and search setup in Test screen.

src/app/views/reports/student-report/student-report.component.html, src/app/views/reports/student-report/student-report.component.scss, src/app/views/reports/student-report/student-report.component.ts
=> Report Dashboard

src/app/views/assignments/popups/test-live/test-live.component.ts
Fix question option selected submission id
=> Fix question option selected submission id

src/app/views/reports/student-report/student-report.component.html, src/app/views/reports/student-report/student-report.component.scss, src/app/views/reports/student-report/student-report.component.ts
=> Solution Sections

src/app/views/reports/student-report/student-report.component.html, src/app/views/reports/student-report/student-report.component.scss
=> Style Sheet Change to report

src/app/views/assignments/models/editTestMetaData.ts, src/app/views/assignments/popups/edit-test/edit-test.component.html, src/app/views/assignments/popups/edit-test/edit-test.component.ts, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/reports/student-report/student-report.component.html
Fix total marks issue:
Hide total marks field for now.
=> Fix total marks issue

src/environments/environment.prod.ts, src/environments/environment.stage.ts, src/environments/environment.ts
=> Update IP addresses

src/app/shared/components/custom-dialog-confirmation/custom-dialog-confirmation.component.html, src/app/shared/components/custom-dialog-confirmation/custom-dialog-confirmation.component.scss, src/app/views/assignments/add-students/add-students.component.html, src/app/views/assignments/add-students/add-students.component.ts
Bug fixes for Test preview Window and assign test to admin/staff
=> Bug fixes for Test preview Window and assign test to admin/staff

src/app/views/assignments/popups/questions-list/questions-list.component.html, src/app/views/assignments/popups/questions-list/questions-list.component.ts, src/app/views/questions/question-management/question-management.component.html
Add Section filter in Add Question popup
=> Add Section filter in Add Question popup

src/app/models/questions/search-question-model.ts, src/app/views/assignments/popups/questions-list/questions-list.component.html, src/app/views/assignments/popups/questions-list/questions-list.component.ts, src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/tests/tests.component.ts, src/app/views/assignments/update-test-content/update-test-content.component.html
Update Questions upload issues in Test Update screen
=> Update Questions upload issues in Test Update screen

src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts
Add Passage , Explanation and Option details for Test Preview/Live
=> Test Preview fixes

src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts
=> Fix question indexes

src/app/app.module.ts, src/app/views/assignments/services/test-config-service.ts, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts, src/app/views/dashboard/admin-dashboard/admin-dashboard.component.html, src/app/views/dashboard/assignment-test/assignment-test.component.html, src/app/views/dashboard/assignment-test/assignment-test.component.scss, src/app/views/dashboard/assignment-test/assignment-test.component.spec.ts, src/app/views/dashboard/assignment-test/assignment-test.component.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.html, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.scss, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.spec.ts, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.ts, src/app/views/reports/student-report/student-report.component.html, src/app/views/reports/student-report/student-report.component.scss, src/app/views/reports/student-report/student-report.component.ts
Admin Dashboard and Ranking tab in student dashboard
=> Admin Dashboard and Ranking tab in student dashboard

src/app/views/assignments/models/editTestMetaData.ts, src/app/views/assignments/popups/edit-test/edit-test.component.html, src/app/views/assignments/popups/edit-test/edit-test.component.ts, src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/update-test-content/update-test-content.component.html
Add tags to the Question Paper
=> Add tags to the Question Paper

src/app/views/reports/student-report/student-report.component.html
Add explanation in Student report
=> Add explanation in Student report

src/app/shared/components/custom-dialog-confirmation/custom-dialog-confirmation-model.ts, src/app/shared/components/custom-dialog-confirmation/custom-dialog-confirmation.component.html, src/app/shared/components/custom-dialog-confirmation/custom-dialog-confirmation.component.ts, src/app/views/assignments/popups/questions-list/questions-list.component.html, src/app/views/assignments/popups/test-live/test-live.component.css, src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/tests/tests.component.css, src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts, src/app/views/assignments/view-assignment/view-assignment.component.ts, src/app/views/dashboard/assignment-test/assignment-test.component.html, src/app/views/dashboard/assignment-test/assignment-test.component.scss, src/app/views/dashboard/assignment-test/assignment-test.component.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.html, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.scss, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.ts
=> Blocker Bug fixes

.vscode/settings.json, src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/update-test-content/update-test-content.component.ts
=> Fix timer issue

src/app/views/assignments/models/editTestMetaData.ts, src/app/views/assignments/popups/edit-test/edit-test.component.css, src/app/views/assignments/popups/edit-test/edit-test.component.html, src/app/views/assignments/popups/edit-test/edit-test.component.ts, src/app/views/assignments/popups/test-live/test-live.component.html
Add Calculator logic on Edit screen
=> Add Calculator logic on Edit screen

src/app/views/assignments/popups/test-live/test-live.component.ts
Fix user experience in Student Live Test.
=> Fix user experience in Student Live Test.

src/app/app.component.ts, src/app/app.module.ts, src/app/models/user/user-model.ts, src/app/state_management/_actions/user.action.ts, src/app/state_management/_reducers/auth.reducers.ts, src/app/views/dashboard/assignment-test/assignment-test.component.scss, src/app/views/dashboard/dashboard.component.ts, src/app/views/dashboard/term-condition-page/term-condition-page.component.html, src/app/views/dashboard/term-condition-page/term-condition-page.component.spec.ts, src/app/views/dashboard/term-condition-page/term-condition-page.component.ts
=> Accept Term and Condition

src/app/views/assignments/popups/test-live/test-live.component.ts
Reduce the time already spent on the previous attempt from the timer.
=> Fix time taken timer

src/app/views/assignments/tests/tests.component.ts, src/app/views/login/login.component.scss, src/styles.scss
Login button text color : wqhite
Remove background image for auto fill
Fix test search to include regex.
=> Set style for login page

src/app/app.module.ts, src/app/shared/components/header/header.component.ts, src/app/shared/pipe/filterPipe.pipe.spec.ts, src/app/shared/pipe/filterPipe.pipe.ts, src/app/views/assignments/popups/calculator/calculator.component.css, src/app/views/assignments/popups/calculator/calculator.component.html, src/app/views/assignments/popups/questions-list/questions-list.component.html, src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/view-assignment/view-assignment.component.html, src/app/views/dashboard/assignment-test/assignment-test.component.html, src/app/views/dashboard/assignment-test/assignment-test.component.ts, src/app/views/dashboard/student-dashboard/student-dashboard.component.css, src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.html, src/app/views/dashboard/test-pending-verification/test-pending-verification.component.ts, src/app/views/questions/question-management/question-management.component.html, src/app/views/reports/student-report/student-report.component.html, src/app/views/reports/student-report/student-report.component.ts, src/app/views/student-batch/student-batch-management/student-batch-management.component.html, src/app/views/user/user-management/user-management.component.html, src/styles.scss
=> Some Bug fixes

src/app/views/assignments/popups/calculator/calculator.component.css, src/app/views/assignments/popups/calculator/calculator.component.html, src/app/views/assignments/popups/test-live/test-live.component.css, src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/tests/tests.component.css, src/app/views/assignments/tests/tests.component.ts
=> Update css for calc

src/app/views/dashboard/term-condition-page/term-condition-page.component.html, src/app/views/dashboard/term-condition-page/term-condition-page.component.ts, src/assets/termAndCondition.html
Update Terms and Condition page
=> Update Terms and Condition page

src/app/views/dashboard/assignment-test/assignment-test.component.ts
Update Admin Dashboard navigation to view result
=> Update Admin Dashboard navigation to view result

src/app/views/assignments/tests/tests.component.ts
=> Update Preview button logic

src/assets/images/delete.svg
=> Remove unused image

src/app/views/assignments/popups/test-live/test-live.component.html, src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/tests/tests.component.ts
=> Fix staff Preview issue

src/app/views/assignments/update-test-content/update-test-content.component.css, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts
=> Stages in Test

src/app/models/questions/question-model.ts, src/app/views/common-component/solution-filter/solution-filter.component.ts, src/app/views/common-component/view-student-assignment-result/student-report.component.html, src/app/views/questions/question-form/question-form.component.ts
Add Very hard Difficulty Level
=> Add Very hard Difficulty Level

.gitignore, package-lock.json, src/app/views/administration/student-batch/student-batch-management/student-batch-management.component.scss, src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts, src/styles.scss
Fix Student Dashboard Performance
=> Fix Student Dashboard Performance

src/app/views/assignments/tests/tests.component.html, src/app/views/assignments/tests/tests.component.ts, src/app/views/dashboard/dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts, src/app/views/questions/question-management/question-management.component.html, src/app/views/questions/question-management/question-management.component.ts
=> Update staff access

src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts
=> Fix Dashboard loading issue

src/app/views/common-component/view-student-assignment-result/student-report.component.html, src/app/views/common-component/view-student-assignment-result/student-report.component.ts
=> Fix reporting issue

src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.ts
Changes for Pagination in Student dashboard
=> Changes for Pagination in Student dashboard

src/app/services/users/users.service.ts, src/app/views/administration/student-batch/bulk-upload-batch-students/bulk-upload-batch-students.component.html, src/app/views/administration/student-batch/bulk-upload-batch-students/bulk-upload-batch-students.component.scss, src/app/views/administration/student-batch/bulk-upload-batch-students/bulk-upload-batch-students.component.ts, src/app/views/administration/student-batch/student-batch-management/student-batch-management.component.scss, src/app/views/administration/user/add-user-dialog/add-user-dialog.component.ts, src/app/views/administration/user/user-management/user-management.component.html, src/app/views/administration/user/user-management/user-management.component.scss, src/app/views/administration/user/user-management/user-management.component.ts, src/app/views/administration/user/user.module.ts, src/app/views/administration/user/view-student-batch-dialog/view-student-batch-dialog.component.html, src/app/views/administration/user/view-student-batch-dialog/view-student-batch-dialog.component.scss, src/app/views/administration/user/view-student-batch-dialog/view-student-batch-dialog.component.spec.ts, src/app/views/administration/user/view-student-batch-dialog/view-student-batch-dialog.component.ts
Batch Management Table and Batch Upload Changes
=> Batch Management Table and Batch Upload Changes

src/app/services/authorization/authorization.service.ts, src/app/services/users/users.service.ts, src/app/views/administration/user/user-management/user-management.component.html, src/app/views/administration/user/user-management/user-management.component.ts, src/app/views/administration/user/view-student-batch-dialog/view-student-batch-dialog.component.html, src/app/views/layout/change-password/change-password.component.html, src/app/views/layout/change-password/change-password.component.ts
=> Reset Password

src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/services/test-config-service.ts, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts, src/app/views/common-component/common-component.module.ts, src/app/views/common-component/view-student-assignment-result/student-report.component.ts
Fix sequencing issue in Preview and Edit test screen
=> Fix sequencing issue in Preview and Edit test screen

src/app/views/assignments/update-test-content/update-test-content.component.ts
=> Sequence Fixes

src/app/views/assignments/popups/test-live/test-live.component.ts, src/app/views/assignments/update-test-content/update-test-content.component.ts
Question sequence with sequence number and passage content
=> Question sequence with sequence number and passage content

src/app/views/assignments/models/postTestVM.ts, src/app/views/assignments/popups/assessment-editor/assessment-editor.component.css, src/app/views/assignments/popups/assessment-editor/assessment-editor.component.html, src/app/views/assignments/popups/assessment-editor/assessment-editor.component.ts, src/app/views/assignments/popups/edit-test/edit-test.component.html, src/app/views/assignments/popups/edit-test/edit-test.component.ts, src/app/views/assignments/tests/tests.component.ts
=> Add Test Type controls on UI

src/app/views/test-management/live-test/live-test.component.html, src/app/views/test-management/live-test/live-test.component.ts
Test Preview Wrong Correct Answer
=> Test Preview Wrong Correct Answer

src/app/views/questions/question-form-preview/question-form-preview.component.html, src/app/views/questions/question-form-preview/question-form-preview.component.ts, src/app/views/questions/question-form/question-form.component.html, src/app/views/questions/question-form/question-form.component.ts
Commit for preview/edit questions for TITA Question Type
=> Commit for preview/edit questions for TITA Question Type

src/app/models/user/user-model.ts, src/app/services/users/users.service.ts, src/app/views/dashboard/student-dashboard/student-dashboard.component.html, src/app/views/dashboard/student-dashboard/student-dashboard.component.scss, src/app/views/reports/student-reports/student-reports.component.html, src/app/views/reports/student-reports/student-reports.component.ts
Pagination for dropdown under reports tab for admin login / click effect on student dashboard icons.
=> Pagination for dropdown / click effect on student dashboard icons.

src/app/views/test-management/live-test-instruction/live-test-instruction.component.html, src/app/views/test-management/live-test-instruction/live-test-instruction.component.ts, src/app/views/test-management/live-test/live-test.component.html, src/app/views/test-management/live-test/live-test.component.ts
Fix question numbering issue in options
=> Fix question numbering issue in options

src/app/views/common-component/solution-right-panel/solution-right-panel.component.html, src/app/views/common-component/solution-right-panel/solution-right-panel.component.scss, src/app/views/common-component/student-assignment-stats-charts/student-assignment-stats-charts.component.html, src/app/views/common-component/view-student-assignment-result/student-report.component.html, src/app/views/common-component/view-student-assignment-result/student-report.component.scss, src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.html, src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.scss, src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.ts, src/app/views/reports/student-reports/student-reports.component.html
Bug Fixes :
Adding search bar on Test Name on student report screen.
resizing of students solutions screen.
=> Sk work branch

src/app/views/common-component/section-wise-summary/section-wise-summary.component.html, src/app/views/common-component/section-wise-summary/section-wise-summary.component.scss, src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts, src/app/views/common-component/view-student-assignment-result/student-report.component.ts, src/app/views/test-management/live-test/live-test.component.ts
=> Test Bug fixes and report

src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.html, src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.ts
Modification of filter on students Reports screen
=> Modification of filter on students Reports screen

src/app/views/assignments/tests/tests.component.html, src/app/views/test-management/live-test/live-test.component.scss
Test Delete and SIngle Select Test Live
=> Test Delete and SIngle Select Test Live

src/app/views/common-component/view-student-assignment-result/student-report.component.ts
Question Sequence in solution Section
=> Question Sequence in solution Section

src/app/views/bootstrap/login/login.component.scss, src/app/views/questions/question-form/question-form.component.html, src/app/views/questions/question-form/question-form.component.ts
Changing Multiple select check box to single select.
Increasing width of login container.
=> Code Modifications

src/app/views/assignments/add-students/add-students.component.html, src/app/views/assignments/add-students/add-students.component.ts
Filters added on path
Test >> View Test >> Full Length Test >> View Assignment
=> Adding Filters

src/app/views/common-component/section-wise-summary/section-wise-summary.component.html, src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts, src/app/views/common-component/solution-right-panel/solution-right-panel.component.html, src/app/views/common-component/solution-right-panel/solution-right-panel.component.ts
Adding accuracy in solution and summary screen
=> Adding accuracy in solution and summary screen

src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts, src/app/views/test-management/live-test/live-test.component.ts
=> Add close handler

src/app/views/common-component/section-wise-summary/section-wise-summary.component.html, src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts
Average Time column added on screen
viewresults -> summary
=> Average Time Column added

src/app/models/reports/student-report-model.ts, src/app/views/common-component/section-wise-summary/section-wise-summary.component.html, src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts, src/app/views/common-component/view-student-assignment-result/student-report.component.html, src/app/views/common-component/view-student-assignment-result/student-report.component.ts
adding Time Distribution Analysis & Question Analysis on summary page in student reports.
Correction for fonts of READ MORE and READ LESS.
=> TimeDistributionAnalysis and QuestionAnalysis

src/app/views/test-management/live-test/live-test.component.ts
=> Bug Fixes -Timer Issue

src/app/views/test-management/live-test/live-test.component.ts
Close Test - if interenet is off
=> Close Test - if interenet is off

src/app/views/test-management/live-test/live-test.component.ts
adding error blocks in live test component
=> adding error blocks in live test component

src/app/views/test-management/live-test/live-test.component.ts
=> Update Live test close handler

src/app/models/questions/search-question-model.ts, src/app/shared/directives/tooltip/custom-tool-tip/custom-tool-tip.component.css, src/app/shared/directives/tooltip/custom-tool-tip/custom-tool-tip.component.html, src/app/shared/directives/tooltip/custom-tool-tip/custom-tool-tip.component.spec.ts, src/app/shared/directives/tooltip/custom-tool-tip/custom-tool-tip.component.ts, src/app/shared/directives/tooltip/tool-tip-renderer.directive.ts, src/app/shared/shared.module.ts, src/app/views/assignments/models/questionMarkedForReview.ts, src/app/views/assignments/popups/questions-list/questions-list.component.css, src/app/views/assignments/popups/questions-list/questions-list.component.html, src/app/views/assignments/popups/questions-list/questions-list.component.ts, src/app/views/common-component/solution-filter/solution-filter.pipe.ts, src/app/views/test-management/live-test/live-test.component.ts
=> Test and filter Bugs

src/app/views/common-component/solution-filter/solution-filter.component.css, src/app/views/common-component/solution-filter/solution-filter.component.html, src/app/views/common-component/view-student-assignment-result/student-report.component.scss
Panel expansion behaviour removed
=> Panel expansion behaviour removed

src/app/views/test-management/live-test/live-test.component.ts
@JupiterWing
Timer Bugs last question response not saved
=> @JupiterWing Timer Bugs last question response not saved 

src/app/services/assignment/test-assignment-service.service.ts, src/app/views/reports/test-report/test-student-table/test-student-table.component.css, src/app/views/reports/test-report/test-student-table/test-student-table.component.html, src/app/views/reports/test-report/test-student-table/test-student-table.component.ts
=> Test Report Download

src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.html, src/app/views/reports/student-reports/student-list-grid/student-list-grid.component.ts
Sorting added on student report screen
=> Sorting added on student report screen

src/app/views/administration/student-batch/add-batch-student/add-batch-student.component.html, src/app/views/administration/student-batch/add-batch-student/add-batch-student.component.scss, src/app/views/administration/student-batch/add-batch-student/add-batch-student.component.ts, src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts
=> Adding Spinner

src/app/views/assignments/popups/assessment-editor/assessment-editor.component.html, src/app/views/assignments/popups/assessment-editor/assessment-editor.component.ts, src/app/views/assignments/popups/test-config/test-config.component.html, src/app/views/assignments/popups/test-config/test-config.component.ts, src/app/views/assignments/tests/tests.component.ts, src/app/views/assignments/update-test-content/update-test-content.component.html, src/app/views/assignments/update-test-content/update-test-content.component.ts
=> Test Types Nmat

src/app/views/test-management/live-test-window/live-test-window.component.html, src/app/views/test-management/live-test-window/live-test-window.component.ts, src/app/views/test-management/nmat-live-test/nmat-live-test.component.html, src/app/views/test-management/nmat-live-test/nmat-live-test.component.scss, src/app/views/test-management/nmat-live-test/nmat-live-test.component.spec.ts, src/app/views/test-management/nmat-live-test/nmat-live-test.component.ts, src/app/views/test-management/test-management.module.ts
=> Nmat Test Integraton

src/app/views/common-component/section-wise-summary/section-wise-summary.component.html, src/app/views/common-component/section-wise-summary/section-wise-summary.component.ts, src/app/views/common-component/view-student-assignment-result/student-report.component.html
=> Difficulty LevelHide

src/app/views/common-component/view-student-assignment-result/student-report.component.html, src/app/views/test-management/live-test-instruction/live-test-instruction.component.html, src/app/views/test-management/live-test-instruction/live-test-instruction.component.scss, src/app/views/test-management/live-test-instruction/live-test-instruction.component.ts, src/app/views/test-management/live-test-window/live-test-window.component.html, src/app/views/test-management/live-test-window/live-test-window.component.ts, src/app/views/test-management/nmat-live-test/nmat-live-test.component.ts, src/environments/environment.ts
NMAT Hide summary from report and question section arrangable for NMAT
=> NMAT Hide summary from report and question section arrangable for NMAT

src/app/views/test-management/live-test-instruction/live-test-instruction.component.html, src/app/views/test-management/nmat-live-test/nmat-live-test.component.ts, src/environments/environment.ts
=> Random Questions

src/app/views/layout/profile/profile.component.ts, src/app/views/questions/question-management/question-management.component.html, src/app/views/questions/question-management/question-management.component.ts
Adding dropdown on question search
=> Adding dropdown on question search

.github/workflows/webpack.yml
=> Create Git Action

src/app/views/test-management/nmat-live-test/nmat-live-test.component.ts
=> Sequence Corrected
